# Generated by Django 4.1.3 on 2024-03-12 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_complete_order_complate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complate',
            new_name='complete',
        ),
    ]
